name: CI

on: [push]

jobs:
  test:
    name: Test

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install mill
        run: brew install mill

      - name: Test openapigen
        run: mill openapigen.test

      - name: Generate kubeclient sources
        run: make kube-client-gen-src

      - name: Test kubeclient
        # Cannot use the default 'mill' script here, as it will ignore JAVA_HOME, and use the latest java, trigerring
        # the following bug that occurs with scala 2.12.x and the latest versions of java:
        # https://github.com/scala/bug/issues/11608
        run: /usr/local/Cellar/mill/0.5.2/libexec/mill kubeclient.test