# TODO: Run actions in containers.

name: CI

on: [push]

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - uses: jodersky/setup-mill@master
        with:
          mill-version: 0.5.3

      - name: Test openapigen
        run: mill openapigen.test

      - name: Generate kubeclient sources
        run: make kube-client-gen-src

      - uses: engineerd/setup-kind@v0.1.0
        with:
          version: "v0.6.0"
          skipClusterCreation: true

      - name: Prepare kind cluster for testing kubeclient
        run: |
          mkdir -p .tmp
          kind create cluster --name test --image "kindest/node:v1.16.3"
          kind get kubeconfig --name test > .tmp/test-kube-conf

      - name: Test kubeclient
        run: mill kubeclient.test

      - name: Publish to sonatype (master branch only)
        if: github.ref == 'refs/heads/master'
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY_B64 }}" | base64 --decode | gpg --batch --import

          mill openapigen.publish \
            --sonatypeCreds "${{ secrets.SONATYPE_USERNAME }}:${{ secrets.SONATYPE_PASSWORD }}" \
            --gpgPassphrase "${{ secrets.GPG_PASSPHRASE }}" \
            --readTimeout 600000 \
            --release false \
            --signed true

          mill kubeclient.publish \
            --sonatypeCreds "${{ secrets.SONATYPE_USERNAME }}:${{ secrets.SONATYPE_PASSWORD }}" \
            --gpgPassphrase "${{ secrets.GPG_PASSPHRASE }}" \
            --readTimeout 600000 \
            --release false \
            --signed true