name: publish-generated-sources

on:
  push:
    branches:
      - master

jobs:
  publish-generated-sources:
    name: Publish Generated Sources

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2-beta
        with:
          fetch-depth: 1

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - uses: jodersky/setup-mill@master
        with:
          mill-version: 0.5.1

      - name: Generate kubeclient sources
        run: make kube-client-gen-src

      - name: Reformat generated sources
        run: mill kubeclient.reformat

      - name: Push generated sources to the 'generated-sources' branch
        run: |
          git config --global user.email "publish-generated-sources@github.action"
          git config --global user.name "Publish Generated Sources (GitHub Action)"
          git add -f ./kubeclient/generatedSrc
          git commit -m "Generated sources for $(git rev-parse --short HEAD)"
          git push -f origin master:generated-sources